### ISSUE TITLE
Problem with inserting nested elements

### ISSUE THREAD

**Issue by misterzorgy** [arsnebula/polymer-quill#6]
I have a problem when trying to set content with code like:

```
<div>a
    <div>b</div>
</div>
```

It throws an error 

quill.js:3445 Uncaught TypeError: Cannot read property 'emit' of undefined
    at Scroll.update (quill.js:3445)
    at MutationObserver.<anonymous> (quill.js:10945)

What can I do to fix this bug?

**Comment by chrismbeckett** [comment]
This repo uses an outdated version of Quill.js and was produced to demonstrate a custom build of QuillJS that could be used with Custom Elements. Unfortunately, I am not in a position to support this going forward.
