### ISSUE TITLE
Why the QuillJs can't work with the other code?

### ISSUE THREAD

**Issue by romulo94** [arsnebula/polymer-quill#7]
Hello, I'm using your code. And i need to know about somethings... 
This code is working in shadow dom or shady?
I have problem, when I use the QuillJs i need too to have the otlher script, it's a function and this function "can read" what i write in meu editor when Quill detect a change. But It's not happens! Because I can't  it. So, Is it possible? And finally... What is it necessary fot the code to be better?  
Thanks guy.

**Comment by chrismbeckett** [comment]
This repo uses an outdated version of Quill.js and was produced to demonstrate a custom build of QuillJS that could be used with Custom Elements. Unfortunately, I am not in a position to support this going forward.
